name: "Bash CI"

on:
  push:
    branches: [ build ]
  pull_request:
    branches: [ build ]

jobs:
  build:
    runs-on: ${{ matrix.os.host }}

    strategy:
      matrix:
        os:
          - name: Windows
            architecture: x64
            host: windows-latest

          - name: Linux
            architecture: x64
            host: ubuntu-latest

          - name: MacOS
            architecture: x64
            host: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Building Libraries
        shell: bash
        run: |
          bash build.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.os.name }}
          path: |
            release/