name: "Build external dependencies"

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os.host }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            architecture: x64
            host: windows-latest

          - name: Linux
            architecture: x64
            host: ubuntu-latest

          - name: MacOS
            architecture: x64
            host: macos-11

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Add MSBuild to PATH
        if: matrix.os.host == 'windows-latest'
        uses: microsoft/setup-msbuild@v1.0.2  

      - name: Building Libraries Windows MSVC
        if: matrix.os.host == 'windows-latest'
        run: dependencies/build.bat

      - name: Building Libraries Windows
        if: matrix.os.host == 'windows-latest'
        shell: bash
        run: |
          bash dependencies/build.sh
          cp -f dependencies/buildLG/libgiflib.dll dependencies/binaries/giflib.dll
          cp -f dependencies/buildLG/liblodepng.dll dependencies/binaries/lodepng.dll

      - name: Upload Artifacts Windows
        uses: actions/upload-artifact@v3
        if: matrix.os.host == 'windows-latest'
        with:
          name: Windows
          path: dependencies/binaries/*.dll

      - name: Building Libraries Linux
        if: matrix.os.host == 'ubuntu-latest'
        shell: bash
        run: |
          bash dependencies/build.sh -all
          cp -f dependencies/buildPC/libpolyclipping.so dependencies/binaries/libpolyclipping.so
          cp -f dependencies/buildJP/libturbojpeg.so dependencies/binaries/libturbojpeg.so
          cp -f dependencies/buildLG/libgiflib.so dependencies/binaries/libgiflib.so
          cp -f dependencies/buildLG/liblodepng.so dependencies/binaries/liblodepng.so

      - name: Upload Artifacts Linux
        uses: actions/upload-artifact@v3
        if: matrix.os.host == 'ubuntu-latest'
        with:
          name: Linux
          path: dependencies/binaries/*.so

      - name: Building Libraries MacOS
        if: matrix.os.host == 'macos-11'
        shell: bash
        run: |
          bash dependencies/build.sh -all
          cp -f dependencies/buildPC/libpolyclipping.dylib dependencies/binaries/libpolyclipping.dylib
          cp -f dependencies/buildJP/libturbojpeg.dylib dependencies/binaries/libturbojpeg.dylib
          cp -f dependencies/buildLG/libgiflib.dylib dependencies/binaries/libgiflib.dylib
          cp -f dependencies/buildLG/liblodepng.dylib dependencies/binaries/liblodepng.dylib

      - name: Upload Artifacts MacOS
        uses: actions/upload-artifact@v3
        if: matrix.os.host == 'macos-11'
        with:
          name: MacOS
          path: dependencies/binaries/*.dylib