name: "Build external dependencies"

on: workflow_dispatch

jobs:
  build:
    runs-on: ${{ matrix.os.host }}

    strategy:
      fail-fast: false
      matrix:
        os:
          - name: Windows
            architecture: x64
            host: windows-latest

          - name: Linux
            architecture: x64
            host: ubuntu-latest

          - name: MacOS
            architecture: x64
            host: macos-11

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - uses: actions/checkout@v3

      - name: Building Libraries Windows
        if: matrix.os.host == 'windows-latest'
        shell: bash
        run: |
          bash dependencies/build.sh
          cp -f dependencies/binaries/jpeg/libturbojpeg.dll dependencies/binaries/libturbojpeg.dll

      - name: Upload Artifacts Windows
        uses: actions/upload-artifact@v3
        if: matrix.os.host == 'windows-latest'
        with:
          name: Windows
          path: dependencies/binaries/*.dll

      - name: Building Libraries Linux
        if: matrix.os.host == 'ubuntu-latest'
        shell: bash
        run: |
          bash dependencies/build.sh
          cp -f dependencies/binaries/jpeg/libturbojpeg.so dependencies/binaries/libturbojpeg.so

      - name: Upload Artifacts Linux
        uses: actions/upload-artifact@v3
        if: matrix.os.host == 'ubuntu-latest'
        with:
          name: Linux
          path: dependencies/binaries/*.so

      - name: Building Libraries MacOS
        if: matrix.os.host == 'macos-11'
        shell: bash
        run: |
          bash dependencies/build.sh
          cp -f dependencies/binaries/jpeg/libturbojpeg.dylib dependencies/binaries/libturbojpeg.dylib

      - name: Upload Artifacts MacOS
        uses: actions/upload-artifact@v3
        if: matrix.os.host == 'macos-11'
        with:
          name: MacOS
          path: dependencies/binaries/*.dylib